FROM ubuntu:22.04

# Set the non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and add the deadsnakes PPA
RUN apt-get update && apt-get install -y \
    software-properties-common \
    git \
    curl \
    && add-apt-repository ppa:deadsnakes/ppa

# Install Python 3.12 and other essential packages
RUN apt-get update && apt-get install -y \
    python3.12 \
    python3.12-venv \
    python3.12-dev \
    cmake \
    gcc \
    g++ \
    libfftw3-dev \
    && apt-get clean

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3.12 get-pip.py && \
    rm get-pip.py

# Update alternatives to set Python 3.12 as the default
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 \
    && update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
    && update-alternatives --set python3 /usr/bin/python3.12 \
    && update-alternatives --set python /usr/bin/python3

RUN mkdir -p /faux_home/measures && \
    curl ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar | tar xvzf - -C /faux_home/measures && \
    echo "measures.directory: /faux_home/measures" > /faux_home/.casarc

ENV CASARCFILES=/faux_home/.casarc

RUN python -mpip install --no-cache-dir --upgrade pip wheel

RUN git clone https://github.com/talonmyburgh/DDFacet.git && \
    cd DDFacet && \
    git checkout SSD3NancepMPI3.12 && \
    cd .. && \
    python -mpip install ./DDFacet

RUN python -mpip install --no-cache-dir "git+https://github.com/caracal-pipeline/stimela"

RUN python -mpip install --no-cache-dir "git+https://github.com/caracal-pipeline/cult-cargo"

# Install meqtrees-cattery
RUN python -mpip install --no-cache-dir "meqtrees-cattery"

# Install DynSpecMS from the specified GitHub repository
RUN python -mpip install --no-cache-dir "git+https://github.com/saopicc/RIMS.git@SplitCatalog_fixes_jax"

# set XDG cache (normally ~/.cache)
ENV XDG_CACHE_HOME /var/cache
ENV XDG_CONFIG_HOME /var/config
RUN mkdir -p /var/cache/astropy /var/config/astropy

RUN python -c "from astropy.config.paths import get_cache_dir, get_config_dir; print(get_cache_dir()); print(get_config_dir())"

# force download of basic astropy data
RUN python -c "from astropy.time import Time; Time.now().ut1"
RUN python -c "from astropy.coordinates import EarthLocation; EarthLocation.of_site('VLA')"

# this now disables astropy downloads so should be done last 
COPY astropy.cfg  /var/config/astropy

CMD {CMD}
