FROM ubuntu:24.04

# Set the non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-dev \
    python3-pip \
    cmake \
    gcc \
    g++ \
    libfftw3-dev \
    git \
    curl \
    && apt-get clean

# Update alternatives so python points to python3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

RUN mkdir -p /faux_home/measures && \
    curl ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar | tar xvzf - -C /faux_home/measures && \
    echo "measures.directory: /faux_home/measures" > /faux_home/.casarc

ENV CASARCFILES=/faux_home/.casarc

ENV PIP_BREAK_SYSTEM_PACKAGES=1

RUN python -m pip install --no-cache-dir wheel

RUN git clone https://github.com/saopicc/DDFacet.git && \
    cd DDFacet && \
    git checkout MassiveMerge_PR_Py3.12 && \
    cd .. && \
    python -m pip install ./DDFacet

# Install meqtrees-cattery
RUN python -m pip install --no-cache-dir "meqtrees-cattery"

# Install DynSpecMS from the specified GitHub repository
RUN python -m pip install --no-cache-dir "git+https://github.com/saopicc/RIMS.git@SplitCatalog_fixes_nojax"

# set XDG cache (normally ~/.cache)
ENV XDG_CACHE_HOME /var/cache
ENV XDG_CONFIG_HOME /var/config
RUN mkdir -p /var/cache/astropy /var/config/astropy

RUN python -c "from astropy.config.paths import get_cache_dir, get_config_dir; print(get_cache_dir()); print(get_config_dir())"

# force download of basic astropy data
RUN python -c "from astropy.time import Time; Time.now().ut1"
RUN python -c "from astropy.coordinates import EarthLocation; EarthLocation.of_site('VLA')"

# this now disables astropy downloads so should be done last 
COPY astropy.cfg  /var/config/astropy

CMD {CMD}