name: Docker

on:
  push:
    branches:
      - master
    paths:
      - inspect_dynspec/images/ms2dynspec/Dockerfile.branch  # Trigger when this file changes
      - '**'  # Trigger for all other changes

env:
  RATT_GITHUB_TOKEN: ${{ secrets.RATT_GITHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_BRANCH: master  # NOTE: Presumes that the latest tag points at master.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Docker login
        run: docker login quay.io --username $DOCKER_USER --password $DOCKER_PASSWORD

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install stimela
        run: pip install git+https://github.com/caracal-pipeline/stimela.git

      - name: Install cult-cargo
        run: pip install git+https://github.com/caracal-pipeline/cult-cargo.git

      - name: Install package
        run: pip install -e .

      - name: Always run inspectdynspec build
        run: build-cargo -m inspect_dynspec/images/cargo-manifest.yml inspectdynspec -a

      - name: Conditionally run ms2dynspec build
        if: ${{ github.event.head_commit.modified && contains(github.event.head_commit.modified, 'inspect_dynspec/images/ms2dynspec/Dockerfile.branch') }}
        run: build-cargo -m inspect_dynspec/images/cargo-manifest.yml ms2dynspec -a