name: Docker

on:
  push:
    branches:
      - master
    paths:
      - '**'  # Trigger for all changes

env:
  RATT_GITHUB_TOKEN: ${{ secrets.RATT_GITHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_BRANCH: master  # NOTE: Presumes that the latest tag points at master.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Docker login
        run: docker login quay.io --username $DOCKER_USER --password $DOCKER_PASSWORD

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          pip install git+https://github.com/caracal-pipeline/stimela.git
          pip install git+https://github.com/caracal-pipeline/cult-cargo.git
          pip install -e .

      - name: Debug - List modified files
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }}

      - name: Always run inspectdynspec build
        run: build-cargo -m inspect_dynspec/images/cargo-manifest.yml inspectdynspec

      - name: Conditionally run ms2dynspec build
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          if echo "$CHANGED_FILES" | grep -q "inspect_dynspec/images/ms2dynspec/Dockerfile.branch"; then
            build-cargo -m inspect_dynspec/images/cargo-manifest.yml ms2dynspec
          else
            echo "No relevant changes detected, skipping ms2dynspec build."
          fi